/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const Modal1LazyImport = createFileRoute('/modal1')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const Modal1LazyRoute = Modal1LazyImport.update({
  path: '/modal1',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/modal1.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/modal1': {
      preLoaderRoute: typeof Modal1LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  Modal1LazyRoute,
])

/* prettier-ignore-end */
